### ISSUE TITLE
Advertise add-on in comments produced by add-on

### ISSUE THREAD

**Issue by mcomella** [agi/move-to-bugzilla#7]
Comments created by the issue currently look like:
> Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1669817

I think they should say something like 
> Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1669817
>
> This change automated by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

Without doing something like this, I fear this add-on isn't very discoverable and folks will continue wasting time moving these bugs by hand. :)

**Comment by agi** [comment]
Advertising, I love it.
